# Generated by Django 4.2.3 on 2023-08-09 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_profile_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='profile',
            managers=[
            ],
        ),
    ]
