# Generated by Django 4.2.3 on 2023-08-11 20:39

import django.core.validators
from django.db import migrations, models
import project_defence.web.validators


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_rename_gamer_name_profile_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(2), project_defence.web.validators.validate_first_name])),
                ('email', models.EmailField(max_length=40)),
                ('password', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(8)])),
            ],
        ),
    ]
