# Generated by Django 4.2.3 on 2023-08-08 15:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_addgames'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddExpert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('games_done', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('image', models.URLField(blank=True, default='static/images/avatar.jpg', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AddKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('image', models.URLField(blank=True, default='static/images/avatar.jpg', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GiftCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=25)),
                ('amount', models.FloatField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='addgames',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addgames',
            name='game_name',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addgames',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='addgames',
            name='producer',
            field=models.CharField(default=1, max_length=20, validators=[django.core.validators.MinLengthValidator(2)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='gamer_name',
            field=models.CharField(default=1, max_length=16, validators=[django.core.validators.MinLengthValidator(2)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
