# Generated by Django 4.2.3 on 2023-08-09 14:19

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_addexpert_addkeys_giftcards_addgames_description_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='profile',
            managers=[
                ('x_object', django.db.models.manager.Manager()),
            ],
        ),
    ]
